repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^frontend/
      - id: trailing-whitespace
        exclude: ^frontend/
      - id: requirements-txt-fixer
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ^(frontend/|setup.py)
        args: ["-m3", "-w100", "--tc"]
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        exclude: ^(frontend/|setup.py)|migrations
        args: [--config=./backend/pyproject.toml]
